In [517]:
import numpy as np
from prompt_toolkit.utils import to_int

print(np.__version__)

2.4.3


In [518]:
board = np.zeros((8,8), dtype=int)
x_coord = ["A","B","C","D","E","F","G","H"]

In [519]:
#Function to place all the pieces for the board
def build_board(play):
    #set spaces that aren't in play
    for i in range(8):
        for j in range(4):
            if i % 2 == 0:
                play[i][2*j] = 9
            else:
                play[i][2*j+1] = 9

    #placing pieces
    for x in range(8):
        for y in range(8):
            if x < 3:
                if play[x][y] == 0:
                    play[x][y] = -1
            if x > 4:
                if play[x][y] == 0:
                    play[x][y] = 1
    return play

#Function to convert board coordinates to grid coordinates
def convert_cords(position):
    x = position[0]
    y = int(position[1:])-1

    for c in range(8):
        if x_coord[c] == x:
            x = c

    if not isinstance(x, int) or y > 7 or y < 0:
        return print("Position is out of range"), ""
    else:
        return x, y

#Function to promote a piece when on final rank
def promotion(play,x,y):
    if y == 0:
        if play[x][y] == 1:
            play[x][y] = 2
    if y == 7:
        if play[x][y] == -1:
            play[x][y] = -2

#Function to find places available to move
def move_piece(play,position):
    x, y = convert_cords(position)
    if not isinstance(x, int) or y > 7 or y < 0:
        return print("Different coordinates needed")
    options = []

    promotion(play,x,y)

    #Find selected pieces potential moves
    if play[x][y] == -1:
        if play[x+1][y+1] == 0 and x != 7 and y != 7:
            options.append([x+1,y+1])
        if play[x+1][y-1] == 0 and x != 7 and y != 0:
            options.append([x+1,y-1])
    elif play[x][y] == 1:
        if play[x-1][y+1] == 0 and x != 0 and y != 7:
            options.append([x-1,y+1])
        if play[x-1][y-1] == 0 and x != 0 and y != 0:
            options.append([x-1,y-1])
    elif play[x][y] == 2 or play[x][y] == -2:
        if y < 7:
            if play[x+1][y+1] == 0 and x != 7 and y != 7:
                options.append([x+1,y+1])
            if play[x-1][y+1] == 0 and x != 0 and y != 7:
                options.append([x-1,y+1])
        if x < 7:
            if play[x+1][y-1] == 0 and x != 7 and y != 0:
                options.append([x+1,y-1])
        if play[x-1][y-1] == 0 and x != 0 and y != 0:
            options.append([x-1,y-1])

    return options

In [520]:
board = build_board(board)
print(board)
move_piece(board,"H5")

[[ 9 -1  9 -1  9 -1  9 -1]
 [-1  9 -1  9 -1  9 -1  9]
 [ 9 -1  9 -1  9 -1  9 -1]
 [ 0  9  0  9  0  9  0  9]
 [ 9  0  9  0  9  0  9  0]
 [ 1  9  1  9  1  9  1  9]
 [ 9  1  9  1  9  1  9  1]
 [ 1  9  1  9  1  9  1  9]]


[]