In [5]:
import numpy as np
print(np.__version__)

2.4.3


In [6]:
board = np.zeros((8,8), dtype=int)

In [7]:
#Function to place all the peices for the board
def build_board(play):
    #set spaces that aren't in play
    for i in range(8):
        for j in range(4):
            if i % 2 == 0:
                play[i][2*j] = 9
            else:
                play[i][2*j+1] = 9

    #placing pieces
    for x in range(8):
        for y in range(8):
            if x < 3:
                if play[x][y] == 0:
                    play[x][y] = -1
            if x > 4:
                if play[x][y] == 0:
                    play[x][y] = 1
    return play

#Function to find places available to move
def move_piece(play,x,y):
    options = []

    #Find selected pieces potential moves
    if play[x][y] == -1:
        if play[x+1][y+1] == 0 and x != 7 and y != 7:
            options.append([x+1,y+1])
        if play[x+1][y-1] == 0 and x != 7 and y != 0:
            options.append([x+1,y-1])
    elif play[x][y] == 1:
        if play[x-1][y+1] == 0 and x != 0 and y != 7:
            options.append([x-1,y+1])
        if play[x-1][y-1] == 0 and x != 0 and y != 0:
            options.append([x-1,y-1])
    else:
        if play[x+1][y+1] == 0 and x != 7 and y != 7:
            options.append([x+1,y+1])
        if play[x+1][y-1] == 0 and x != 7 and y != 0:
            options.append([x+1,y-1])
        if play[x-1][y+1] == 0 and x != 0 and y != 7:
            options.append([x-1,y+1])
        if play[x-1][y-1] == 0 and x != 0 and y != 0:
            options.append([x-1,y-1])

    return options

In [8]:
board = build_board(board)
print(board)

move_piece(board,2,1)

[[ 9 -1  9 -1  9 -1  9 -1]
 [-1  9 -1  9 -1  9 -1  9]
 [ 9 -1  9 -1  9 -1  9 -1]
 [ 0  9  0  9  0  9  0  9]
 [ 9  0  9  0  9  0  9  0]
 [ 1  9  1  9  1  9  1  9]
 [ 9  1  9  1  9  1  9  1]
 [ 1  9  1  9  1  9  1  9]]


[[3, 2], [3, 0]]